import type { Metadata } from "next";
import { montserrat } from "./fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Frontend Mentor | Product preview card component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
